openapi: 3.0.0
info:
  title: Paper Trail API Service
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check for the service
      responses:
        200:
          description: OK
components:
  schemas:
    Family:
      type: object
      properties:
        family_id:
          type: integer
          format: int64
        family_name:
          type: string
        family_members:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        principal_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
