openapi: 3.1.0
info:
  title: Paper Trail API Service
  version: 1.0.0
components:
  schemas:
    Family:
      family_id:
        type: integer
        format: int64
      family_name:
        type: string
      family_members:
        type: array
        schema:
          $ref: "#/components/schemas/User"
    User:
      user_id:
        type: integer
        format: int64
      principal_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
